Appliescontroller
Vigrouze/freementors pull request #13
Opened 2021-11-23 16:48 UTC by alhd7892

Applies controller done

2021-11-23 16:52 UTC, Joelebucheron approved these changes

2021-11-24 08:39 UTC, ndgdl commented on app/controllers/applies_controller.rb
> +    params.require(:apply).permit(:status, :motivation, :mission_id, :padawan_id)
I don't think we need the "status" and "padawan_id" in the params since status is generated automatically and padawan_id will be the current user.

2021-11-24 08:45 UTC, ndgdl requested changes
Everything's good except for the '@apply.save' missing to add! 👍

2021-11-24 08:45 UTC, ndgdl commented on app/controllers/applies_controller.rb
> +    @apply.padawan = current_user
Missing the last step to save it in the DB:
`@apply.save`

2021-11-24 08:45 UTC, ndgdl commented on app/controllers/applies_controller.rb
>      redirect_to mentor_profil_path
Wondering if the approve or deny shouldn't be in the mission crontroller since we're only manipulation `@missions`

2021-11-24 08:55 UTC, Vigrouze commented
All good, i agree with Nico on 'apply.save' in create and in fact, we should ask a TA if we need to put the 'accept' and 'deny' actions in mission controller

2021-11-24 10:38 UTC, ndgdl approved these changes
All good!

2021-11-24 10:39 UTC, Joelebucheron approved these changes

2021-11-24 10:40 UTC, merged